name: CI Workflow

on:
  pull_request:
    branches:
      - nest-js-backend    # Or the name of the default branch of your repository

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use the Node.js version appropriate for your project

      - name: Install dependencies
        run: |
          npm ci   # or `npm install` if you're not using a lock file

      - name: Run tests
        run: |
          npm run test

      - name: Build the application
        run: |
          npm run build
